name: Test
on:
    push:
      branches: [ "*" ]
    pull_request:
      branches: [ "*" ]
  

permissions:
  contents: read # for checkout

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:

    - name: Install Pkl
      uses: pkl-community/setup-pkl@v0
      with:
        pkl-version: "0.28.2"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install --no-install-recommends --no-upgrade -y just

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run tests
      run: just test
